### ISSUE TITLE
Package not found when installing with yarn

### ISSUE THREAD

**Issue by PeterBowater** [strapi/strapi-starter-gatsby-corporate#25]
Using documented yarn install command:

`yarn create strapi-starter my-site gatsby-corporate`

We get :

`[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/create-strapi-corporate-gatsby: Not found".`

Noted that the package is not found on npmjs registry if you manually search.

Seems to be working with npx :) 

Thanks :)

**Comment by bingalls** [comment]
I don't get a package not found error. There's almost no difference for me, between yarn v2 & npx. However:
* Latest node v17 is rejected. After downgrading to v16.13,
* WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  See https://v8.dev/blog/math-random for details

I get to the prompt; it makes no difference, whether I choose *Quick Start* or manual, yarn or npx.

> This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
> SyntaxError: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at getPackageInfo (\~/.npm/_npx/ecd569b0a81a6814/node_modules/create-strapi-starter/utils/fetch-npm-starter.js:19:27)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>     at async getStarterInfo (\~/.npm/_npx/ecd569b0a81a6814/node_modules/create-strapi-starter/utils/build-starter.js:109:26)
>     at async buildStarter (\~/.npm/_npx/ecd569b0a81a6814/node_modules/create-strapi-starter/utils/build-starter.js:133:7)

**Comment by safejace** [comment]
got the same error as @bingalls 

is there anyway to get this starter working with strapi 4?
