### ISSUE TITLE
Failed to install starter

### ISSUE THREAD

**Issue by LucasZapico** [strapi/strapi-starter-gatsby-corporate#30]
The following install command [found in the strapi docs](https://strapi.io/starters/strapi-starter-gatsby-corporate) fails with the following error. 

```shell
npx create-strapi-starter my-site gatsby-corporate
```
__Error__

```shell
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Command failed with exit code 1: npm view gatsby-corporate name version --silent
    at makeError (/Users/luca/.npm/_npx/ecd569b0a81a6814/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/luca/.npm/_npx/ecd569b0a81a6814/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getPackageInfo (/Users/luca/.npm/_npx/ecd569b0a81a6814/node_modules/create-strapi-starter/utils/fetch-npm-starter.js:27:22)
    at async getStarterInfo (/Users/luca/.npm/_npx/ecd569b0a81a6814/node_modules/create-strapi-starter/utils/build-starter.js:109:26)
    at async buildStarter (/Users/luca/.npm/_npx/ecd569b0a81a6814/node_modules/create-strapi-starter/utils/build-starter.js:133:7)
```

--- 
System Notes

- macOS v11.4
- node v17.3.0
- Gatsby v4.5.0

**Comment by mjolliffe** [comment]
I have the same issue.

**Comment by Koruyo** [comment]
same

**Comment by SachinAmarasinghe** [comment]
This starter kit uses Strapi  4 by default, whereas the Gatsby starter doesn't support Strapi 4. Try installing the starter with Strapi 3

`npx create-strapi-starter@3.6.8 my-site gatsby-corporate`

**Comment by bureauberg** [comment]
I first tried to install this starter with npx create-strapi-starter my-site gatsby-corporate (so Strapi v4) but that didn't work out (lots of errors in dependencies)
Then I tried Strapi V3 using 'npx create-strapi-starter@3.6.8 my-site gatsby-corporate, as suggested above but that throws even more errors.

Too bad. It was a nice starter. 

Local: 
w10
node v14.18.3
npm 8.3.2

**Comment by SachinAmarasinghe** [comment]
@bureauberg Since you mentioned I ran a fresh installation with V3 and it still works perfectly for me. I'm running 
Windows 11
node v14.18.1
npm 6.14.15

**Comment by EzraEn1** [comment]
Encountered this issue and figured out why it fails. 

1. The README utilizes starter shorthand for the installation instruction.
2. Starter shorthand assumes the starter package is available on NPM.
3. There is no package available called [@strapi/starter-gatsby-corporate](https://www.npmjs.com/search?q=%40strapi%2Fstarter-gatsby-corporate) as is expected by the starter fetch script.

Long-term fix would be to re-publish the package to NPM.

Workaround is to clone this repo locally and _without_ `cd`ing into it, running either:

```npx create-strapi-starter your-site ./path/to/strapi-starter-gatsby-corporate```
`yarn create strapi-starter your-site ./path/to/strapi-starter-gatsby-corporate`
